services:
  - type: web
    name: eblg-proxy
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      NODE_VERSION: 18
